# this is workflow
name: hello ci/cd workflow

on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: hello dosto
        run: echo "hello dosto"

      - name: say hello to username
        run: echo "hello ${{ github.actor }}"
